AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test Pipeline Lambda
Resources:
  hellofunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: hello_country.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambdacode/hello_country.py
      Description: Sample SAM Lambda Deployment
      Events:
        LambdaSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)        
  

